### ISSUE TITLE
Please update site?

### ISSUE THREAD

**Issue by anjaw3f** [jhonalino/polkaview.network#3]
Hi, since this issue has been fixed and there is no minimum stake required anymore, can this please be updated, so users don't get confused and miss out on staking rewards? 

Thank you!

**Comment by jhonalino** [comment]
@anjaw3f  this is 
![Screen Shot 2021-05-12 at 4 15 16 AM](https://user-images.githubusercontent.com/13143458/117966435-c011bc80-b2d8-11eb-8fc9-ba160ff9ca67.png)

**Comment by anjaw3f** [comment]
Great, thank you!
